const assert=require("node:assert/strict"),{createGame}=require("./game-test-harness");
let checks=0;function test(name,fn){fn();checks++;console.log("PASS "+name);}
function start(g){g.run('Arcade.progress.settle("fixture");intermission=null;startSinglePlayer();closeClassMenu();');}
function choice(g){g.advance(651);g.run('chooseMazeReward(mazeState.rewardOptions[0].id);confirmMazeReward();');g.advance(281);}
test("training attacks travel, misses stay misses, and every class hits from its weapon",()=>{
 for(const hero of ["warrior","ranger","mage","rogue","paladin","bard"]){const g=createGame();start(g);g.run(`equipClass(${JSON.stringify(hero)});player.x=trainingDummy.x-150;player.y=trainingDummy.y;mouseWorld=RogueTraining.targetPoint(trainingDummy);shootAt(mouseWorld.x,mouseWorld.y);`);const hp=g.run('trainingDummy.hp');g.run('updatePlayerProjectiles(1/60)');assert.equal(g.run('trainingDummy.hp'),hp);assert.ok(g.run('playerProjectiles.length')>0);g.run('updatePlayerProjectiles(.3)');assert.ok(g.run('trainingDummy.hp')<hp,hero);g.run('RogueTraining.reset();player.attackCooldown=0;mouseWorld={x:player.x-100,y:player.y-100};shootAt(mouseWorld.x,mouseWorld.y);updatePlayerProjectiles(1);');assert.equal(g.run('trainingDummy.hp'),g.run('trainingDummy.maxHp'));
 }
 const g=createGame();start(g);g.run('RogueTraining.incoming=true;RogueTraining.update(.1);updateHazards(.1);');assert.equal(g.run('hazards.length'),1,"practice bolts survive starter-room updates");
});
test("all eleven optional contracts complete through their actual objective actions",()=>{
 for(const kind of ["cola","burger","fries","trio","sauce","shake","nacho","pizza","donut","taco","sushi"]){const g=createGame();start(g);g.run(`loadBoss(${JSON.stringify(kind)});startMazeForBoss(boss.kind);player.invulnerableTimer=999;mazeState.enemies.slice().forEach(e=>damageBossTarget(e,9999,"Test"));`);
  if(["cola","fries","shake","sushi"].includes(kind))g.run('for(const n of mazeState.contract.nodes){player.x=n.x;player.y=n.y;if(mazeState.contract.mode==="battery"&&!mazeState.contract.carrying)RogueContracts.interact(player,true,true,0);RogueContracts.interact(player,false,true,2.1);}');
  if(kind==="trio")g.run('for(const n of mazeState.contract.nodes){player.x=n.x;player.y=n.y;while(n.orientation!==n.desired)RogueContracts.interact(player,true,false,0);}RogueContracts.update(3.1);');
  if(["sauce","nacho"].includes(kind))g.run('RogueContracts.update(.1);');
  if(kind==="burger")g.run('for(const n of mazeState.contract.nodes){player.x=n.x;player.y=n.y;RogueContracts.interact(player,true,false,0);player.x=mazeState.bounds.x+mazeState.bounds.w*.82;player.y=mazeState.bounds.y+mazeState.bounds.h*.76;RogueContracts.interact(player,true,false,0);}');
  if(kind==="pizza")g.run('player.x=mazeState.contract.nodes[0].x;player.y=mazeState.contract.nodes[0].y;RogueContracts.interact(player,true,false,0);player.x=mazeState.contract.nodes[1].x;player.y=mazeState.contract.nodes[1].y;RogueContracts.interact(player,true,false,0);');
  if(kind==="donut")g.run('for(const n of mazeState.contract.nodes){player.x=n.x;player.y=n.y;RogueContracts.interact(player,false,false,0);}RogueContracts.interact(player,true,false,0);');
  if(kind==="taco")g.run('RogueContracts.update(.1);for(const n of mazeState.contract.nodes){player.x=n.x;player.y=n.y;RogueContracts.interact(player,true,false,0);}');
  g.run('RogueContracts.update(.01);');assert.equal(g.run('mazeState.rewardPending'),true,kind);assert.equal(g.run('Arcade.progress.profile.journal.contracts.length'),1,kind);choice(g);assert.equal(g.run('mazeState.exitOpen'),true);g.run('player.x=mazeState.exit.x+35;player.y=mazeState.exit.y+35;player.gateCooldown=0;updateRoom(.1);');assert.equal(g.run('player.room'),"arena",kind);assert.equal(g.run('debugReportState.lastErrorAtByKey.size'),0);
 }
});
test("contract timeout opens the boss route without awarding currency",()=>{const g=createGame();start(g);g.run('startMazeForBoss("cola");RogueContracts.update(61);');assert.equal(g.run('mazeState.exitOpen'),true);assert.equal(g.run('Arcade.progress.total()'),0);assert.equal(g.run('mazeState.rewardPending'),false);});
test("profile settlement is idempotent across death, reload, milestones and final clear",()=>{
 const g=createGame();start(g);g.run('Arcade.progress.record("bosses","cola");Arcade.progress.record("bosses","cola");Arcade.progress.record("contracts","cola");RogueGame.end("death");');assert.equal(g.run('Arcade.progress.profile.marks'),4);const saved=g.run('localStorage.getItem("boss-fight.profile.v2")');const restored=createGame({storage:{"boss-fight.profile.v2":saved}});restored.run('Arcade.progress.settle("death");');assert.equal(restored.run('Arcade.progress.profile.marks'),4);start(restored);restored.run('Arcade.progress.record("bosses","cola");RogueGame.end("End Run");');assert.equal(restored.run('Arcade.progress.profile.marks'),5);start(restored);restored.run('for(const id of ["cola","burger","fries","trio","sauce","shake","nacho","pizza","donut","taco","sushi"])Arcade.progress.record("bosses",id);RogueGame.end("victory",true);');assert.equal(restored.run('Arcade.progress.profile.lastResult.earned'),20);
});
test("unfinished solo encounters resume health, gear, build, currency and once-per-run saves",()=>{const g=createGame();start(g);g.run('equipClass("mage");enterBossArena();boss.hp=1234;player.hp=72;player.potions=1;RogueCombat.state.saves.timeLoop=true;Arcade.progress.record("contracts","cola");RogueGame.saveCheckpoint();');const saved=g.run('localStorage.getItem("boss-fight.profile.v2")');const restored=createGame({storage:{"boss-fight.profile.v2":saved}});restored.run('RogueGame.resume();');assert.equal(restored.run('player.room'),"arena");assert.equal(restored.run('boss.hp'),1234);assert.equal(restored.run('player.hp'),72);assert.equal(restored.run('player.potions'),1);assert.equal(restored.run('currentClassKey()'),"mage");assert.equal(restored.run('RogueCombat.state.saves.timeLoop'),true);assert.equal(restored.run('Arcade.progress.total()'),1);});
test("build slots, prerequisites, locked purchases and refunds preserve the next-run build",()=>{const g=createGame();g.run('Arcade.progress.profile.marks=100;for(const id of ["melee_iron_hp","melee_blood_bleed","melee_blood_deep","melee_iron_wall","melee_iron_heal","melee_iron_last","warrior_earth_worldsplitter"])Arcade.progress.purchase(id);');assert.equal(g.run('Arcade.progress.select("melee",["melee_iron_hp","melee_blood_bleed","melee_blood_deep","melee_iron_wall","melee_iron_last"])'),true);assert.equal(g.run('Arcade.progress.select("melee",["melee_iron_last","warrior_earth_worldsplitter"])'),false);assert.equal(g.run('Arcade.progress.select("melee",["melee_iron_hp","melee_blood_bleed","melee_blood_deep","melee_iron_wall","melee_iron_heal"])'),false);g.run('Arcade.progress.refund("melee_blood_bleed");');assert.equal(g.run('Arcade.progress.selection("melee").includes("melee_blood_deep")'),false);start(g);assert.equal(g.run('learnTalent("melee_blood_bleed")'),false);assert.equal(g.run('Arcade.progress.refund("melee_iron_hp")'),false);});

function party(count=2){const gs=Array.from({length:count},()=>createGame());const room={id:"regression",state:"inGame",hostId:"p0",players:gs.map((_,i)=>({id:"p"+i,name:"Hero "+i}))};gs.forEach((g,i)=>g.run(`multiplayer.mode="multiplayer";multiplayer.enabled=true;multiplayer.connected=true;multiplayer.id="p${i}";multiplayer.room=${JSON.stringify(room)};multiplayer.socket={readyState:1};var outbound=[];sendServer=m=>{outbound.push(m);return true;};beginRun("multiplayer");closeClassMenu();`));
 function relay(){for(let pass=0;pass<30;pass++){let count=0;gs.forEach((from,i)=>{for(const m of JSON.parse(from.run('JSON.stringify(outbound.splice(0))'))){count++;gs.forEach((to,j)=>{if(i===j)return;const msg=m.type==="event"?{type:"peer-event",id:"p"+i,event:m.event}:m.type==="state"?{type:"peer-state",id:"p"+i,state:m.state}:null;if(msg)to.run(`handleMultiplayerMessage(${JSON.stringify(msg)});`);});}});if(!count)return;}throw new Error("Unbounded relay");}relay();return {gs,host:gs[0],client:gs[1],relay};}
test("two-player client talents resolve through host receipts; duplicates and stale hits cannot deal damage",()=>{const {host,client,gs,relay}=party();gs.forEach(g=>g.run('markPartyReady("starter");'));relay();client.run('runState.learnedTalents=new Set(["melee_blood_bleed"]);player.x=boss.x-70;player.y=boss.y;damageBossTarget(boss,46,"Shot");');const packet=client.run('JSON.stringify(outbound.find(m=>m.event?.kind==="hit-intent"))'),hp=host.run('boss.hp');relay();assert.ok(host.run('boss.hp')<hp);assert.ok(host.run('boss.bleedTimer')>0);const after=host.run('boss.hp');host.run(`handleMultiplayerEvent("p1",${packet}.event);`);assert.equal(host.run('boss.hp'),after);host.run(`handleMultiplayerEvent("p1",{...${packet}.event,seq:999,phaseSeq:-1});`);assert.equal(host.run('boss.hp'),after);assert.equal(host.run('RogueCombat.state.saves.timeLoop||false'),false);});
test("Bard aura metadata and Paladin shields affect teammates without requiring their talents",()=>{const {host,client,relay}=party();host.run('equipClass("bard");runState.learnedTalents=new Set(["bard_hymn_haste","bard_heal_power","bard_heal_armor"]);player.x=350;player.y=450;useAbility(1);useAbility(3);sendMultiplayerState(true);');client.run('player.x=355;player.y=450;player.hp=player.maxHp;player.abilityCooldowns=[5,0,0,0];sendMultiplayerState(true);');relay();const cd=client.run('player.abilityCooldowns[0]');client.run('updateAbilities(1);');assert.ok(client.run('player.abilityCooldowns[0]')<cd-1);assert.ok(client.run('player.rogueShield')>0);host.run('equipClass("paladin");runState.learnedTalents=new Set(["paladin_guard_shared"]);player.abilityCooldowns=[0,0,0,0];useAbility(3);');relay();assert.ok(client.run('player.rogueShield')>=client.run('player.maxHp*.1'));});
test("four-player party wipe ends the run once; host departure banks confirmed earnings once",()=>{const {gs,host,client,relay}=party(4);gs.forEach(g=>g.run('markPartyReady("starter");'));relay();gs.forEach(g=>g.run('Arcade.progress.record("contracts","cola");damagePlayer(99999,"Wipe",{fixed:true,ignoreOverlapGrace:true});sendMultiplayerState(true);'));relay();host.run('update(.1);');relay();gs.forEach(g=>{assert.equal(g.run('RogueGame.finished'),true);assert.equal(g.run('Arcade.progress.profile.marks'),1);assert.equal(g.run('Arcade.screens.current.id'),"resultsOverlay");});client.run('handleMultiplayerEvent("p0",{kind:"run-end",phaseSeq:multiplayer.phaseSeq,bossKind:boss.kind,seq:1,reason:"party wipe",contracts:["cola"]});');assert.equal(client.run('Arcade.progress.profile.marks'),1);
 const p=party();p.client.run('Arcade.progress.record("bosses","cola");returnToMultiplayerLobby("Host left. Confirmed progress banked.");returnToMultiplayerLobby("Host left.");');assert.equal(p.client.run('Arcade.progress.profile.marks'),3);
});
test("damage-over-time budgets, proc isolation, refunds and defensive caps stay bounded",()=>{
 const g=createGame();start(g);g.run('equipClass("warrior");runState.learnedTalents=new Set(["melee_blood_bleed","melee_blood_deep","melee_earth_after","melee_iron_wall","warrior_earth_worldsplitter"]);applyGear();RogueCombat.resetRun();trainingDummy.maxHp=10000;trainingDummy.hp=10000;applyBleed(trainingDummy);');
 const tick=g.run('Math.round(trainingDummy.bleedDamage)');g.run('for(let i=0;i<14;i++)updateRogueDebuffs(trainingDummy,.5);');assert.equal(g.run('trainingDummy.hp'),10000-tick*12,"six-second Bleed has exactly twelve ticks");
 g.run('trainingDummy.hp=10000;trainingDummy.bleedTimer=0;damageBossTarget(trainingDummy,40,"Shot",{proc:true});');assert.equal(g.run('trainingDummy.bleedTimer'),0,"a proc cannot reapply on-basic Bleed");
 g.run('player.shieldWallTimer=5;RogueCombat.effect({type:"consecration",x:player.x,y:player.y,r:150,ttl:5});RogueCombat.state.smokeGrace=RogueCombat.clock+5;player.hp=player.maxHp;player.invulnerableTimer=0;var hpBefore=player.hp;damagePlayer(100,"Cap fixture",{fixed:true,ignoreOverlapGrace:true});');assert.ok(g.run('hpBefore-player.hp')>=30,"combined mitigation cannot exceed 70%");
 g.run('equipClass("ranger");runState.learnedTalents=new Set(["ranger_deadeye_refund"]);trainingDummy.hp=10000;trainingDummy.markedTimer=0;player.abilityCooldowns=[20,0,0,0];markBossTarget(trainingDummy);for(let i=0;i<4;i++)damageBossTarget(trainingDummy,27,"Shot",{rangedBasic:true});');const cd=g.run('player.abilityCooldowns[0]');g.run('for(let i=0;i<8;i++)damageBossTarget(trainingDummy,27,"Shot",{rangedBasic:true});');assert.equal(g.run('player.abilityCooldowns[0]'),cd,"one mark application grants one refund");g.run('RogueCombat.refund(0,1000);');assert.equal(g.run('player.abilityCooldowns[0]'),0);
});
test("projectile block healing counts an attack once, Blink returns once, and bosses resist pulls",()=>{
 const g=createGame();start(g);g.run('equipClass("warrior");runState.learnedTalents=new Set(["melee_iron_heal","warrior_vanguard_shield_hook"]);player.hp=player.maxHp*.5;var hpBefore=player.hp;var a=RogueTraining.aim();hazards=Array.from({length:6},(_,i)=>({type:"mazeShot",attackId:"one-volley",x:a.origin.x+Math.cos(a.angle)*(30+i),y:a.origin.y+Math.sin(a.angle)*(30+i),vx:1,vy:1,r:6,ttl:3,damage:5}));useAbility(0);');assert.equal(g.run('player.hp-hpBefore'),g.run('Math.ceil(player.maxHp*.02)'));
 g.run('enterBossArena();player.x=boss.x-55;player.y=boss.y;mouseWorld={x:boss.x,y:boss.y};var bx=boss.x,by=boss.y;player.abilityCooldowns[0]=0;useAbility(0);');assert.equal(g.run('boss.x'),g.run('bx'));assert.equal(g.run('boss.y'),g.run('by'));
 g.run('equipClass("mage");runState.buildLocked=false;runState.learnedTalents=new Set(["mage_chrono_blink"]);player.x=world.arena.x+250;player.y=world.arena.y+250;mouseWorld={x:player.x+300,y:player.y};var origin={x:player.x,y:player.y};player.abilityCooldowns=[0,0,0,0];useAbility(2);var cd=player.abilityCooldowns[2];useAbility(2);');assert.equal(g.run('player.x'),g.run('origin.x'));assert.equal(g.run('player.y'),g.run('origin.y'));assert.equal(g.run('player.abilityCooldowns[2]'),g.run('cd'));g.run('useAbility(2);');assert.equal(g.run('player.x'),g.run('origin.x'));
});
test("overheal shields refresh without stacking; holy strips help teammates only inside their shape",()=>{
 const {host,client,relay}=party();host.run('equipClass("bard");runState.learnedTalents=new Set(["bard_heal_power"]);player.x=350;player.y=450;player.hp=player.maxHp;player.abilityCooldowns=[0,0,0,0];useAbility(3);');for(let i=0;i<8;i++)host.run('updateAbilities(.5);');assert.ok(host.run('player.rogueShield')<=host.run('Math.ceil(player.maxHp*.05)'));
 host.run('equipClass("paladin");runState.learnedTalents=new Set(["paladin_consecrate_sunlit_march"]);abilityEffects=[];player.x=350;player.y=450;mouseWorld={x:600,y:450};player.abilityCooldowns=[0,0,0,0];useAbility(2);sendMultiplayerState(true);');relay();client.run('player.x=410;player.y=440;var fast=playerSpeed();player.y=600;var normal=playerSpeed();');assert.ok(Math.abs(client.run('fast/normal')-1.1)<.0001);
});
test("quick co-op objective presses reach the host and duplicate presses do not rotate twice",()=>{
 const {gs,host,client,relay}=party();gs.forEach(g=>g.run('loadBoss("trio");startMazeForBoss("trio",{fromParty:true,sequence:1});'));relay();client.run('var n=mazeState.contract.nodes[0];player.x=n.x;player.y=n.y;sendMultiplayerState(true);RogueContracts.interactHeld=false;RogueContracts.interactPressed=true;RogueContracts.syncTimer=1;RogueContracts.update(.016);');const packet=client.run('JSON.stringify(outbound.find(m=>m.event?.kind==="contract-action"))'),before=host.run('mazeState.contract.nodes[0].orientation');relay();assert.equal(host.run('mazeState.contract.nodes[0].orientation'),(before+1)%3);host.run(`handleMultiplayerEvent("p1",${packet}.event);`);assert.equal(host.run('mazeState.contract.nodes[0].orientation'),(before+1)%3);
});
test("Sushi body hits retain Mark, Poison, fire explosions, area damage and once-per-shot identity",()=>{
 const g=createGame();start(g);g.run('loadBoss("sushi");enterBossArena();var s=sushiSegments().find(s=>s.weak);player.x=s.x-80;player.y=s.y;mouseWorld={x:s.x,y:s.y};equipClass("ranger");player.abilityCooldowns=[0,0,0,0];useAbility(0);updatePlayerProjectiles(.3);');assert.ok(g.run('boss.markedShots')>0);
 g.run('equipClass("rogue");var s=sushiSegments()[3];player.x=s.x-70;player.y=s.y;mouseWorld={x:s.x,y:s.y};player.attackCooldown=0;shootAt(s.x,s.y);updatePlayerProjectiles(.3);');assert.ok(g.run('boss.poisonStacks')>0);
 g.run('equipClass("mage");runState.learnedTalents=new Set(["mage_pyro_burn"]);var s=sushiSegments()[3];player.x=s.x-80;player.y=s.y;mouseWorld={x:s.x,y:s.y};player.abilityCooldowns=[0,0,0,0];useAbility(0);updateAbilities(.3);updatePlayerProjectiles(.3);');assert.ok(g.run('boss.burnTimer')>0,"Fire Blast explodes and applies its purchased Burn");
 const hp=g.run('boss.hp');g.run('var tail=sushiSegments().at(-1);damageEnemiesInRadius(tail.x,tail.y,35,20,"Area fixture",[],{proc:true});');assert.ok(g.run('boss.hp')<hp,"a field on the tail damages the body once");
 g.run('var s=sushiSegments()[3];var p={x:s.x,y:s.y,vx:0,vy:0,r:10,damage:20,ttl:1,tag:"Ranged",piercing:true};hitSushiSegment(p);var onceHp=boss.hp;hitSushiSegment(p);');assert.equal(g.run('boss.hp'),g.run('onceHp'));
});
test("reload preserves defeated Trio bottles and disabled Pizza stations",()=>{
 for(const kind of ["trio","pizza"]){const g=createGame();start(g);g.run(`loadBoss(${JSON.stringify(kind)});enterBossArena();player.hp=77;player.abilityCooldowns=[1,2,3,4];${kind==="trio"?'condimentBosses[0].hp=0;condimentBosses[1].hp=123;':'boss.toppingParts[0].hp=0;boss.toppingParts[0].disabledUntil=RogueCombat.clock+4;'}RogueGame.saveCheckpoint();`);const saved=g.run('localStorage.getItem("boss-fight.profile.v2")'),restored=createGame({storage:{"boss-fight.profile.v2":saved}});restored.run('RogueGame.resume();');assert.equal(restored.run('player.hp'),77);assert.equal(restored.run('player.abilityCooldowns[2]'),3);if(kind==="trio"){assert.equal(restored.run('condimentBosses[0].hp'),0);assert.equal(restored.run('condimentBosses[1].hp'),123);}else{assert.equal(restored.run('boss.toppingParts[0].hp'),0);assert.equal(restored.run('boss.toppingParts[0].disabledUntil-RogueCombat.clock'),4);}}
});
console.log(checks+" roguelite mechanics regression groups passed.");
