/* Every purchasable ID has explicit, bounded gameplay handlers. */
(function(){
  const C=RogueCombat,R=(id,event,fn)=>C.rule(id,event,fn),A=()=>C.A(),S=()=>C.state;
  const direct=c=>!c.proc, quake=c=>c.type==="quake", basic=c=>c.basic&&direct(c);
  const hit=(c,name)=>c.source===name&&direct(c), inField=(type,t)=>C.inside(type,t);
  const pendingBleed=t=>(t.bleedTimer||0)*(t.bleedDamage||0)*2;
  const pendingPoison=t=>(t.poisonTimer||0)*(t.poisonDamagePerStack||0)*(t.poisonStacks||0);
  const targetsNear=(t,r)=>livingBosses().filter(n=>n!==t&&distance(n,t)<=r+n.radius);
  const shieldSave=(key,hp,wall,invul,c)=>{if(S().saves[key])return;S().saves[key]=true;player.hp=Math.ceil(player.maxHp*hp);player.shieldWallTimer=Math.max(player.shieldWallTimer,wall);player.invulnerableTimer=Math.max(player.invulnerableTimer,invul);c.saved=true;showFloat(key);};
  const repeat=(c,fraction,delay=.35)=>{const pos={...c.start},origin={...c.origin},angle=c.angle;C.later(delay,()=>{if(c.type==="quake")C.pulse(pos.x,pos.y,142*(c.radiusMultiplier||1),A()*1.18*c.factor*fraction,"Quake Echo");else if(c.type==="smite")C.pulse(c.center?.x||origin.x,c.center?.y||origin.y,c.r||96,A()*1.12*c.factor*fraction,"Smite Echo");else if(c.type==="chord")for(const t of livingBosses()){const p=RogueTraining.targetPoint(t);if(distance(origin,p)<212+t.radius&&Math.abs(angleDifference(Math.atan2(p.y-origin.y,p.x-origin.x),angle))<Math.PI*.28)damageBossTarget(t,c.damageAmount*fraction,"Chord Echo",{proc:true});}else C.pulse(origin.x,origin.y,90,A()*fraction,"Bulwark Echo");});};

  R("melee_iron_hp","block",c=>{if(c.blocked>0)C.shield(.05);});
  R("warrior_vanguard_shield_hook","hit afterHit",c=>{if(!hit(c,"Shield Bash"))return;if(c.event==="hit"&&!c.target.mazeEnemy)c.amount*=1.25;if(c.event==="afterHit"&&c.target.mazeEnemy){const t=c.target,dx=player.x-t.x,dy=player.y-t.y,d=Math.hypot(dx,dy)||1;t.x+=dx/d*Math.min(70,d);t.y+=dy/d*Math.min(70,d);}});
  R("warrior_vanguard_brace","tick cast",c=>{if(c.event==="tick"){S().brace=(player.moving?0:(S().brace||0)+c.dt);if(S().brace>=.5)S().braceUntil=C.clock+2;}else if(c.type==="bash"&&S().braceUntil>=C.clock){c.halfAngle=Math.PI/3;c.factor*=1.35;S().braceUntil=0;}});
  R("melee_iron_wall","cast",c=>{if(c.type==="wall")c.durationBonus=2;});
  R("melee_iron_heal","block",c=>{if(c.blocked)C.heal(Math.min(.08,(c.attacksBlocked??c.blocked)*.02));});
  R("warrior_vanguard_counterquake","prevented block cast",c=>{if(c.event==="cast"&&quake(c)){c.factor*=1+.2*(S().quakeCharges||0);S().quakeCharges=0;}else if((c.event==="block"&&c.blocked>0||c.event==="prevented"&&c.prevented>0)&&C.ready("quakeChargeAt",1))S().quakeCharges=Math.min(3,(S().quakeCharges||0)+1);});
  R("warrior_vanguard_bulwark_echo","castEnd",c=>{if(["bash","quake","whirlwind"].includes(c.type)&&S().echoReady>C.clock){S().echoReady=0;repeat(c,.4);}});
  R("melee_iron_last","lethal block afterHit",c=>{if(c.event==="lethal")shieldSave("Unmoving Mountain",.25,3,1.5,c);else if(c.event==="block"&&c.blocked>0&&player.shieldWallTimer>0)S().guardBasic=true;else if(basic(c)&&S().guardBasic){S().guardBasic=false;C.pulse(c.target.x,c.target.y,12,A(),"Guard Counter");}});
  R("melee_blood_bleed","afterHit",c=>{if(basic(c))applyBleed(c.target);});
  R("melee_blood_whirl","hit afterHit",c=>{if(!hit(c,"Whirlwind Dash"))return;if(c.event==="hit"&&c.target.bleedTimer>0)c.amount*=1.25;else if(c.event==="afterHit")applyBleed(c.target);});
  R("melee_blood_deep","bleed",c=>{c.duration=6;c.tickDamage=A()*.08;});
  R("warrior_blood_price","cast",c=>{if(quake(c))c.healthShortcut=.06;});
  R("melee_blood_hemo","afterHit",c=>{if(!hit(c,"Groundbreaker"))return;const t=c.target;if(t.bleedTimer>0){const seconds=Math.min(3,t.bleedTimer);t.bleedTimer-=seconds;C.pulse(t.x,t.y,12,seconds*t.bleedDamage*2*1.5,"Hemorrhage");}else applyBleed(t,{timer:2});});
  R("warrior_blood_crimson_trail","dash",c=>{if(c.type==="whirlwind")C.effect({type:"bloodTrail",...c.origin,x2:c.destination.x,y2:c.destination.y,r:28,ttl:3,pulseTimer:0});});
  R("warrior_blood_reaver_rhythm","hit afterHit",c=>{if(!direct(c))return;const previous=S().lastReaverBasic;if(c.event==="hit"&&!c.basic&&previous===true)c.amount*=1.15;if(c.event==="afterHit"){if(previous!==undefined&&previous!==c.basic&&c.target.bleedTimer>0)c.target.bleedTimer=Math.min(6,c.target.bleedTimer+1);S().lastReaverBasic=c.basic;}});
  R("warrior_blood_bloodstorm","afterHit",c=>{if(!hit(c,"Whirlwind Dash")||!C.once(c.cast,"bloodstorm-"+c.target.name))return;const t=c.target;if(t.bleedTimer>0){const amount=Math.min(2*A(),pendingBleed(t)*1.5);t.bleedTimer=0;C.pulse(t.x,t.y,12,amount,"Bloodstorm");if(C.once(c.cast,"bloodstormFinish"))C.pulse(player.x,player.y,92,A()*.5,"Bloodstorm Finish");}else applyBleed(t);});
  R("melee_earth_radius","cast hit",c=>{if(c.event==="cast"&&quake(c))c.radiusMultiplier=1.25;if(c.event==="hit"&&hit(c,"Groundbreaker")&&distance(c.cast.start,c.target)>142*1.25*.75)c.amount*=1.2;});
  R("warrior_earth_stonefist","quakeEnd afterHit",c=>{if(c.event==="quakeEnd"){S().stoneHits=3;S().stoneUntil=C.clock+5;}else if(basic(c)&&S().stoneHits>0&&S().stoneUntil>C.clock){S().stoneHits--;C.pulse(c.target.x,c.target.y,48,A()*.25,"Stonefist");}});
  R("warrior_earth_fault_line","quakeEnd",c=>{const cast=c.cast,origin=pointFromAngle(cast.start.x,cast.start.y,cast.angle,180);C.effect({type:"faultLine",...cast.start,x2:origin.x,y2:origin.y,r:30,ttl:.4});for(const t of livingBosses())if(distance(cast.start,t)>c.r+t.radius&&rogueSegmentHits(cast.start.x,cast.start.y,origin.x,origin.y,t,30))damageBossTarget(t,A()*.6,"Fault Line",{proc:true});});
  R("melee_earth_after","quakeEnd",c=>repeat(c.cast,.45,.45));
  R("melee_earth_bash","cast afterHit",c=>{if(c.event==="cast"&&c.type==="bash"){c.rangeMultiplier=1.25;c.factor*=1.3;}else if(hit(c,"Shield Bash")&&c.target.mazeEnemy&&distance(c.cast.origin,c.target)>c.cast.range*.8)c.target.rogueStagger=.4;});
  R("warrior_earth_rubble_guard","quakeEnd",c=>C.effect({type:"rubbleGuard",...c.cast.start,r:c.r,ttl:1,blocks:3}));
  R("melee_earth_cap","quakeEnd",c=>{const cleared=destroyProjectilesInRadius(c.cast.start.x,c.cast.start.y,c.r);C.refund(1,Math.min(2,cleared*.5));});
  R("warrior_earth_worldsplitter","quakeEnd",c=>{if(C.count("worldsplitter")%3)return;const hits=new Map();for(let i=0;i<3;i++)C.later(i*.15,()=>{const p=pointFromAngle(c.cast.start.x,c.cast.start.y,c.cast.angle,75+i*65);C.effect({type:"worldWave",...p,r:92,ttl:.3});for(const t of livingBosses())if(distance(p,t)<=92+t.radius&&(hits.get(t)||0)<2){hits.set(t,(hits.get(t)||0)+1);damageBossTarget(t,A()*.6,"Worldsplitter",{proc:true});}});});
  R("warrior_earth_titan_stance","cast defense",c=>{if(c.event==="cast"&&quake(c)&&livingBosses().some(t=>distance(player,t)<120+t.radius)){c.factor*=1.2;S().titanUntil=C.clock+2;}else if(c.event==="defense"&&S().titanUntil>C.clock)c.multiplier*=.85;});

  R("ranger_deadeye_mark","mark",c=>{c.pips=Math.max(c.pips,6);c.duration=Math.max(c.duration,8);});
  R("ranger_deadeye_damage","hit tick",c=>{if(c.event==="tick"){const a=aimAngle();S().steadyAim=!player.moving&&Math.abs(angleDifference(a,S().lastAim??a))<.06?(S().steadyAim||0)+c.dt:0;S().lastAim=a;}else if(basic(c)&&c.target.markedShots>0){c.options.markedMultiplier=1.65;if(S().steadyAim>=.3)c.amount*=1.15;}});
  R("ranger_deadeye_pierce","cast hit",c=>{if(c.event==="cast"&&c.type==="mark")c.pierce=true;if(c.event==="hit"&&hit(c,"Marked Shot")&&!c.target.mazeEnemy)c.amount*=1.35;});
  R("ranger_deadeye_tumble","dash hit",c=>{if(c.event==="dash"&&c.type==="tumble")S().precisionUntil=C.clock+4;if(c.event==="hit"&&basic(c)&&S().precisionUntil>C.clock){c.amount*=1.6;S().precisionUntil=0;}});
  R("ranger_deadeye_refund","afterHit",c=>{if(c.lastMark&&C.ready("markRefund-"+c.target.rogueMarkId,60))C.refund(0,currentAbilities()[0].cooldown*.35);});
  R("ranger_deadeye_detonation","afterHit death",c=>{if((c.lastMark||c.event==="death"&&c.target.markedShots>0)&&C.ready("markDetonate-"+c.target.rogueMarkId,60))C.pulse(c.target.x,c.target.y,80,A()*.8,"Marked Detonation");});
  R("ranger_deadeye_distance","hit",c=>{const d=distance(player,c.target);if(basic(c)&&c.target.markedShots>0&&d>=180&&d<=320)c.amount*=1.25;});
  R("ranger_deadeye_cap","mark hit afterHit",c=>{if(c.event==="mark"){c.pips=Math.max(c.pips,6);}else if(c.event==="hit"&&basic(c)&&c.target.markedShots>0)c.amount*=1+clamp((.5-c.target.hp/c.target.maxHp),0,.5);else if(c.lastMark&&c.target.hp/c.target.maxHp<.2)C.pulse(c.target.x,c.target.y,12,A(),"Execution Mark");});
  R("ranger_trap_tumble","dash",c=>{if(c.type==="tumble")C.trap(c.origin.x,c.origin.y,true);});
  R("ranger_trap_size","field trapShot",c=>{if(c.event==="field"&&c.type==="trap")c.field.r*=1.4;if(c.event==="trapShot"&&c.field.shotsRemaining===(c.field.pocket?3:c.field.reloads>1?3:5))c.amount*=1.3;});
  R("ranger_trap_barbed","afterHit hit",c=>{if(c.event==="afterHit"&&hit(c,"Trap Arrow")){if(c.target.mazeEnemy)C.slow(c.target,.35,2);else c.target.rogueWoundedUntil=C.clock+2;}else if(c.event==="hit"&&basic(c)&&c.target.rogueWoundedUntil>C.clock)c.amount*=1.2;});
  R("ranger_trap_chain","field",c=>{if(c.type==="trap"&&!c.field.pocket){const traps=abilityEffects.filter(e=>e.type==="volleyTrap"&&!e.pocket);for(const trap of traps.slice(0,-2))trap.ttl=0;}});
  R("ranger_trap_damage","trapShot",c=>{c.amount*=1.3;c.field.arrows=(c.field.arrows||0)+1;if(c.field.arrows%3===0){c.piercing=true;if(!c.target.mazeEnemy)c.amount*=1.25;}});
  R("ranger_trap_tripwire","trapTrigger trapShot",c=>{const marked=livingBosses().find(t=>t.markedShots>0&&distance(t,c.field)<320+t.radius);if(c.event==="trapShot"&&marked)c.target=marked;if(c.event==="trapTrigger"&&marked)marked.markedShots=Math.min(6,marked.markedShots+1);});
  R("ranger_trap_snare_field","tick",()=>{const traps=abilityEffects.filter(e=>e.type==="volleyTrap"&&e.ttl>0);for(let i=0;i<traps.length;i++)for(let j=i+1;j<traps.length;j++){const a=traps[i],b=traps[j],key=a.id+":"+b.id;if(distance(a,b)>220||S()[key])continue;const t=livingBosses().find(t=>rogueSegmentHits(a.x,a.y,b.x,b.y,t,4));if(t){S()[key]=true;C.pulse(t.x,t.y,12,A()*.8,"Tripwire");if(t.mazeEnemy)t.rogueStagger=1;}}});
  R("ranger_trap_cap","field",c=>{if(c.type==="trap"&&!c.field.pocket){c.field.reloads=3;c.field.ttl=12;c.field.maxTtl=12;const traps=abilityEffects.filter(e=>e.type==="volleyTrap");for(const e of traps.slice(0,-2))e.ttl=0;}});
  R("ranger_storm_radius","field stormPulse",c=>{if(c.event==="field"&&c.type==="storm")c.field.r*=1.25;if(c.event==="stormPulse"&&c.field.pulses===1)for(const t of c.hits){if(t.mazeEnemy)C.slow(t,.25,1);else C.pulse(t.x,t.y,12,A()*.2,"Broad Storm");}});
  R("ranger_storm_pulses","field",c=>{if(c.type==="storm")c.field.pulseInterval=.45/1.25;});
  R("ranger_storm_follow","stormTick",c=>{if(!S().steerStorm)return;const e=c.field,p=clampCombatPoint(mouseWorld.x,mouseWorld.y,e.r),dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1,step=Math.min(d,90*c.dt);e.x+=dx/d*step;e.y+=dy/d*step;});
  R("ranger_storm_duration","field",c=>{if(c.type==="storm"){c.field.ttl+=1.2;c.field.maxTtl+=1.2;}});
  R("ranger_storm_marking","stormPulse",c=>{if(c.field.pulses===1)for(const t of c.hits){if(t.markedShots>0)t.markedShots=Math.min(6,t.markedShots+1);else C.mark(t,2,4);}});
  R("ranger_storm_cyclone","dash",c=>{const field=C.inside("arrowStorm");if(c.type==="tumble"&&field&&!field.cyclone){field.cyclone=true;C.pulse(player.x,player.y,90,A()*.6,"Cyclone Step");}});
  R("ranger_storm_cloudburst","cast",c=>{const e=C.inside("arrowStorm");if(["mark","trap"].includes(c.type)&&e&&(e.cloudbursts||0)<2){e.cloudbursts=(e.cloudbursts||0)+1;C.pulse(e.x,e.y,e.r,A()*.35,"Cloudburst");}});
  R("ranger_storm_cap","afterHit stormEnd",c=>{if(c.event==="afterHit"&&basic(c)){const e=C.inside("arrowStorm",c.target);if(e)e.charges=Math.min(5,(e.charges||0)+1);}else if(c.event==="stormEnd"&&!c.field.finished){c.field.finished=true;C.pulse(c.field.x,c.field.y,c.field.r,A()*(.8+.2*(c.field.charges||0)),"Skyfall");}});
  R("ranger_storm_endless_quiver","afterHit",c=>{if(basic(c)&&C.inside("arrowStorm",c.target)&&C.count("quiver")%3===0)C.pulse(c.target.x,c.target.y,12,A()*.4,"Falling Arrow");});

  R("mage_pyro_burn","blastEnd",c=>c.hits.forEach(t=>applyBurn(t)));
  R("mage_pyro_radius","cast hit",c=>{if(c.event==="cast"&&c.type==="blast")c.radiusMultiplier=1.25;if(c.event==="hit"&&hit(c,"Fire Blast")&&distance(c.cast.impactPoint||c.cast.origin||player,RogueTraining.targetPoint(c.target))<35)c.amount+=A()*.3;});
  R("mage_pyro_kindling","dash",c=>{if(c.type==="blink")C.effect({type:"kindlingRune",...c.origin,r:48,ttl:3,triggered:new Set()});});
  R("mage_pyro_damage","cast afterHit",c=>{if(c.event==="cast"&&c.type==="blast")c.factor*=1.25;else if(hit(c,"Fire Blast")&&c.target.burnTimer>0){const time=Math.min(2,c.target.burnTimer);c.target.burnTimer-=time;C.pulse(c.target.x,c.target.y,12,time*c.target.burnDamage*2,"Combustion");}});
  R("mage_pyro_molten_splash","meteorImpact",c=>{for(const t of c.hits)if(t.burnTimer>0&&C.ready("lava-"+t.name,1))C.effect({type:"lavaPatch",x:t.x,y:t.y,r:58,ttl:2,pulseTimer:0});});
  R("mage_pyro_chain_ignite","death",c=>{if(c.target.burnTimer<=0)return;const near=targetsNear(c.target,150).slice(0,2);if(near.length)near.forEach(t=>{applyBurn(t);t.burnTimer=c.target.burnTimer;});else if(C.ready("igniteRefund",1))C.refund(0,1);});
  R("mage_pyro_flame_debt","cast",c=>{if(c.type==="blast")c.healthShortcut=.05;});
  R("mage_pyro_cap","cast blastEnd",c=>{if(c.event==="cast"&&c.type==="blast"){c.inferno=C.count("inferno")%3===0;if(c.inferno)c.factor*=1.75;}else if(c.event==="blastEnd"){c.hits.forEach(t=>applyBurn(t));if(c.cast.inferno)C.effect({type:"infernoField",x:c.projectile.x,y:c.projectile.y,r:c.projectile.explosionRadius,ttl:3,pulseTimer:0});}});
  R("mage_meteor_radius","field",c=>{if(c.type==="meteor")c.field.r*=1.25;});
  R("mage_meteor_speed","field",c=>{if(c.type==="meteor"){c.field.impactInterval/=1.25;c.field.ttl=(c.field.total-1)*c.field.impactInterval+.6;c.field.maxTtl=c.field.ttl;}});
  R("mage_meteor_duration","field",c=>{if(c.type==="meteor"){c.field.remaining+=2;c.field.total+=2;c.field.ttl+=1.2;c.field.maxTtl+=1.2;}});
  R("mage_meteor_gravity","meteorTick hit",c=>{if(c.event==="meteorTick"){const e=c.field;for(const t of livingBosses())if(distance(t,e)<e.r+t.radius&&t.mazeEnemy){const dx=e.x-t.x,dy=e.y-t.y,d=Math.hypot(dx,dy)||1;moveMazeEnemy(t,dx/d*45*c.dt,dy/d*45*c.dt);}}else if(hit(c,"Meteor Field")&&!c.target.mazeEnemy){const e=C.field("meteorField");if(e&&distance(e,c.target)<e.r/2)c.amount*=1.15;}});
  R("mage_meteor_impact_echo","meteorImpact",c=>{if(c.field.impactCount%3===0)C.later(.35,()=>C.pulse(c.x,c.y,58,c.amount*.4,"Impact Echo"));});
  R("mage_meteor_star_brand","afterHit",c=>{if(hit(c,"Meteor Field"))c.target.starBrandUntil=C.clock+5;else if(hit(c,"Fire Blast")&&c.target.starBrandUntil>C.clock){c.target.starBrandUntil=0;C.pulse(c.target.x,c.target.y,12,A()*.8,"Star Brand");}});
  R("mage_meteor_armor","tick defense",c=>{if(c.event==="tick"&&C.inside("meteorField"))S().meteorWardUntil=C.clock+.75;else if(c.event==="defense"&&S().meteorWardUntil>C.clock)c.multiplier*=.8;});
  R("mage_meteor_cap","meteorEnd",c=>{if(!c.field.finished){c.field.finished=true;C.pulse(c.field.x,c.field.y,90,A()*(1.5+Math.min(.6,c.field.targets.size*.15)),"Cataclysm");}});
  R("mage_meteor_orbiting_star","cast afterHit",c=>{if(c.event==="cast"&&c.type==="blast")S().starUntil=C.clock+5;else if(basic(c)&&S().starUntil>C.clock){S().starUntil=0;C.pulse(c.target.x,c.target.y,12,A()*.5,"Orbiting Star");}});
  R("mage_chrono_radius","field tick",c=>{if(c.event==="field"&&c.type==="warp")c.field.r*=1.25;if(c.event==="tick"){const e=C.inside("timeWarp");if(e&&!e.radiusWard){e.radiusWard=true;C.shield(.05,1);}}});
  R("mage_chrono_duration","field",c=>{if(c.type==="warp"){c.field.ttl+=1.5;c.field.maxTtl+=1.5;}});
  R("mage_chrono_blink","cast dash",c=>{if(c.event==="cast"&&c.type==="blink")c.rangeMultiplier=1.2;else if(c.event==="dash"&&c.type==="blink")S().blinkReturn={...c.cast.start,until:C.clock+2};});
  R("mage_chrono_frozen_second","afterHit",c=>{const e=C.inside("timeWarp",c.target);if(!direct(c)||!e)return;e.hitCounts ||= new Map();const n=(e.hitCounts.get(c.target)||0)+1;e.hitCounts.set(c.target,n);if(n===3){if(c.target.mazeEnemy)c.target.rogueStagger=.6;else C.later(.35,()=>C.pulse(c.target.x,c.target.y,12,A()*.6,"Frozen Second"));}});
  R("mage_chrono_borrowed_time","cast",c=>{const e=C.inside("timeWarp");if(!e||!["blast","meteor"].includes(c.type))return;e.refunds ||= [0,0];for(let i=0;i<2;i++)if(i!==c.index&&e.refunds[i]<2.4){const amount=Math.min(.8,2.4-e.refunds[i]);e.refunds[i]+=amount;C.refund(i,amount);}});
  R("mage_chrono_delayed_blast","blastEnd",c=>{const e=C.inside("timeWarp",c.projectile);if(e){const p=c.projectile;C.effect({type:"delayedBlast",x:p.x,y:p.y,r:p.explosionRadius,ttl:.8});C.later(.8,()=>C.pulse(p.x,p.y,p.explosionRadius,p.damage*.4,"Delayed Blast"));}});
  R("mage_chrono_rewind_ward","tick",()=>{const e=C.inside("timeWarp");if(e&&!e.rewindWard){e.rewindWard=true;C.shield(.1,3);const expiry=C.clock+3;C.later(3,()=>{if(player.rogueShield>0&&player.rogueShieldUntil<=expiry+.01)C.refund(2,1);});}});
  R("mage_chrono_cap","lethal afterHit",c=>{if(c.event==="lethal"){if(S().saves.timeLoop)return;shieldSave("timeLoop",.3,0,1,c);const pos=S().history?.find(h=>C.clock-h.at>=1.9);if(pos){const p=constrainToRoom(pos.x,pos.y);player.x=p.x;player.y=p.y;}}else if(basic(c)){const e=C.inside("timeWarp");if(e&&!e.timeEcho){e.timeEcho=true;C.later(.3,()=>C.pulse(c.target.x,c.target.y,12,A()*.5,"Time Echo"));}}});

  R("rogue_venom_stacks","poison",c=>{c.target.poisonStacks=Math.min(7,c.target.poisonStacks);});
  R("rogue_venom_damage","poison",c=>{c.target.poisonDamagePerStack=A()*.035*1.25;});
  R("rogue_venom_cloud","field",c=>{if(c.type==="cloud"){c.field.r*=1.25;c.field.ttl+=1;c.field.maxTtl+=1;}});
  R("rogue_venom_volatile","death afterDamage",c=>{const t=c.target;if(t.poisonStacks<=0)return;let trigger=c.event==="death";if(c.event==="afterDamage"&&!t.mazeEnemy&&t.kind!=="trainingDummy"){const old=Math.floor((1-c.before/t.maxHp)*4),now=Math.floor((1-t.hp/t.maxHp)*4);trigger=now>old;}if(trigger&&C.ready("volatile-"+t.name, .25)){C.pulse(t.x,t.y,90,A()*.6,"Volatile Toxin");for(const n of targetsNear(t,90))C.poison(n,2,false);}});
  R("rogue_smoke_poison","smokePulse",c=>{for(const t of livingBosses())if(distance(t,c.field)<c.field.r+t.radius)C.poison(t,1,false);});
  R("rogue_venom_bloom","poison",c=>{if(c.old<c.max&&c.target.poisonStacks>=c.max&&C.ready("bloom-"+c.target.name,3)){const near=targetsNear(c.target,130).slice(0,2);if(near.length)near.forEach(t=>C.poison(t,2,false));else C.pulse(c.target.x,c.target.y,12,A()*.5,"Toxin Bloom");}});
  R("rogue_venom_bank","poison hit",c=>{if(c.event==="poison"&&c.direct){if(C.count("venomApplications")%3===0)S().venomCharges=Math.min(3,(S().venomCharges||0)+1);}else if(hit(c,"Backstab")&&C.once(c.cast,"venomBank")){c.cast.venomBonus=.2*(S().venomCharges||0);S().venomCharges=0;}if(c.event==="hit"&&hit(c,"Backstab"))c.amount*=1+(c.cast.venomBonus||0);});
  R("rogue_venom_cap","afterHit",c=>{if(!hit(c,"Backstab"))return;const t=c.target,max=C.has("rogue_venom_stacks")?7:5;if(t.poisonStacks>=max){const amount=Math.min(1.5*A(),pendingPoison(t));t.poisonStacks=2;C.pulse(t.x,t.y,12,amount,"Venom Nova");}else if(!t.poisonStacks)C.poison(t,3,true);});
  R("rogue_venom_plague_artist","field cloudTick",c=>{if(c.event==="field"){if(c.type==="cloud"){c.field.ttl=4;c.field.maxTtl=4;}return;}const t=S().lastPoisonedBoss;if(!t||t.hp<=0)return;const e=c.field,dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy)||1,step=Math.min(d,70*c.dt);e.x+=dx/d*step;e.y+=dy/d*step;});
  R("rogue_shadow_backstab","cast afterHit",c=>{if(c.event==="cast"&&c.type==="backstab")c.factor*=1.25;else if(hit(c,"Backstab")&&C.rear(c.target))C.expose(c.target);});
  R("rogue_shadow_exposed","hit afterHit",c=>{if(c.event==="afterHit"&&hit(c,"Backstab"))S().exposedBasicUntil=C.clock+3;if(c.event==="hit"&&basic(c)&&c.target.exposedStacks>0&&S().exposedBasicUntil>C.clock){c.amount*=1.3;S().exposedBasicUntil=0;}});
  R("rogue_shadow_step","cast hit",c=>{if(c.event==="cast"&&c.type==="shadowstep"){c.rangeMultiplier=1.2;S().longShadowUntil=C.clock+3;}else if(hit(c,"Backstab")&&S().longShadowUntil>C.clock)c.amount*=1.3;});
  R("rogue_shadow_ambush_echo","dash",c=>{if(c.type==="shadowstep"){const p={...c.destination};C.later(.25,()=>C.pulse(p.x,p.y,70,A()*.6,"Ambush Echo"));}});
  R("rogue_shadow_expose_bleed","afterHit",c=>{if(hit(c,"Backstab")&&c.target.exposedStacks>0)applyBleed(c.target,{damage:A()*.075,timer:4});});
  R("rogue_shadow_death_mark","hit afterHit",c=>{if(!hit(c,"Backstab"))return;if(c.event==="hit"&&c.target.exposedStacks>0&&c.target.poisonStacks>=3)c.amount*=1.2;else if(c.event==="afterHit")C.poison(c.target,1,true);});
  R("rogue_shadow_knife_dance","death afterHit",c=>{if(!hit(c,"Backstab"))return;if(c.event==="death"&&C.once(c.cast,"knifeRefund"))C.refund(2,currentAbilities()[2].cooldown*.5);else if(c.event==="afterHit"&&!c.target.mazeEnemy&&C.rear(c.target)&&C.once(c.cast,"knifeRefund"))C.refund(2,currentAbilities()[2].cooldown*.2);});
  R("rogue_shadow_cap","hit afterHit",c=>{if(!hit(c,"Backstab"))return;if(c.event==="hit"){c.cast.exposedToConsume=c.target.exposedStacks||0;c.amount*=1+.3*Math.min(3,c.cast.exposedToConsume);}else{if(c.cast.exposedToConsume){c.target.exposedStacks=0;c.target.exposedTimer=0;}else C.expose(c.target);if(C.rear(c.target)&&C.once(c.cast,"deathblowRefund"))C.refund(0,currentAbilities()[0].cooldown*.3);}});
  R("rogue_smoke_size","field tick hit",c=>{if(c.event==="field"&&c.type==="smoke")c.field.r*=1.25;if(c.event==="tick"){const e=C.inside("smokeBomb");if(e&&!e.smokeBasic){e.smokeBasic=true;S().smokeBasicUntil=C.clock+2;}}else if(c.event==="hit"&&basic(c)&&S().smokeBasicUntil>C.clock){c.amount*=1.25;S().smokeBasicUntil=0;}});
  R("rogue_smoke_duration","field smokeTick",c=>{if(c.event==="field"&&c.type==="smoke"){c.field.ttl+=1.5;c.field.maxTtl+=1.5;}if(c.event==="smokeTick"&&distance(player,c.field)<=c.field.r+player.radius)S().smokeGrace=C.clock+.5;});
  R("rogue_smoke_cap","field",c=>{if(c.type==="smoke"){const cleared=destroyProjectilesInRadius(c.field.x,c.field.y,c.field.r);C.refund(2,Math.min(2,cleared*.5));}});
  R("rogue_smoke_step","dash",c=>{if(c.type==="shadowstep"&&C.inside("smokeBomb",c.origin))S().untargetableUntil=C.clock+.75;});
  R("rogue_smoke_noxious_cover","poison",c=>{if(c.direct&&C.inside("smokeBomb",c.target)&&C.ready("noxious-"+c.target.name,1))C.pulse(c.target.x,c.target.y,12,A()*.2,"Noxious Cover");});
  R("rogue_smoke_blind_spot","hit",c=>{if(hit(c,"Backstab")&&C.inside("smokeBomb",c.target)&&!C.rear(c.target))c.amount*=1.3;});
  R("rogue_smoke_vanishing_act","hurt",c=>{if(c.hit>=player.maxHp*.2&&C.ready("vanishing",20))C.smoke(player.x,player.y,2,true);});
  R("rogue_smoke_blackout","field hit",c=>{if(c.event==="field"&&c.type==="smoke"){c.field.ttl++;c.field.maxTtl++;c.field.slowFactor=.4;c.field.blackoutShots=3;}else if(basic(c)){const e=C.inside("smokeBomb");if(e&&e.blackoutShots>0){e.blackoutShots--;c.amount*=1.35;}}});

  R("paladin_consecrate_size","field",c=>{if(c.type==="consecration"){c.field.r*=1.25;C.shield(.05,2);C.support?.("shield",.05,c.field.r,2,c.field.id);}});
  R("paladin_consecrate_duration","field",c=>{if(c.type==="consecration"){c.field.ttl+=1.5;c.field.maxTtl+=1.5;}});
  R("paladin_consecrate_damage","field holyPulse",c=>{if(c.event==="field"&&c.type==="consecration")c.field.damageMultiplier*=1.25;if(c.event==="holyPulse")for(const t of c.hits){t.holyBurnTimer=2;t.holyBurnTick=.5;t.holyBurnDamage=A()*.05;}});
  R("paladin_consecrate_footing","tick",()=>{if(C.inside("consecration"))S().footingUntil=C.clock+.75;});
  R("paladin_consecrate_edge","afterHit",c=>{if(basic(c)&&C.inside("consecration"))C.pulse(c.target.x,c.target.y,60,A()*.25,"Radiant Edge");});
  R("paladin_consecrate_cap","consecrationTick",()=>{S().divineRecovery=C.inside("consecration")?.15:0;});
  R("paladin_consecrate_echo","smiteEnd",c=>{if(C.inside("consecration"))repeat(c.cast,.4);});
  R("paladin_consecrate_cathedral","field consecrationTick consecrationEnd",c=>{if(c.event==="field"&&c.type==="consecration")c.field.baseR=c.field.r;if(c.event==="consecrationTick"){const e=c.field;e.r=(e.baseR||128)*(1+.3*Math.min(1,e.age/2));const inside=distance(player,e)<=e.r+player.radius;if(!inside&&e.cathedralWasInside&&!e.cathedralShield){e.cathedralShield=true;C.shield(.08,3);}e.cathedralWasInside=inside;}if(c.event==="consecrationEnd"&&!c.field.finished){c.field.finished=true;C.pulse(c.field.x,c.field.y,c.field.r,A(),"Cathedral");}});
  R("paladin_consecrate_sunlit_march","dash",c=>{if(c.type==="aegis")C.effect({type:"holyStrip",...c.origin,x2:c.destination.x,y2:c.destination.y,r:24,ttl:3,pulseTimer:0,speedBuff:.1});});
  R("paladin_guard_heal","guard",c=>{if(c.type==="bulwark"){C.heal(.06);C.support?.("heal",.06,180,0,c.cast.id);}});
  R("paladin_guard_mitigation","defense",c=>{if(player.shieldWallTimer>0)c.guardMultiplier=.4;});
  R("paladin_guard_projectiles","dash",c=>{if(c.type==="aegis"){let cleared=0;hazards=hazards.filter(h=>{if(Number.isFinite(h.vx)&&rogueSegmentHits(c.origin.x,c.origin.y,c.destination.x,c.destination.y,{...h,radius:h.r},30)){cleared++;return false;}return true;});if(cleared)C.shield(.08);}});
  R("paladin_guard_vow","prevented hit",c=>{if(c.event==="prevented"&&player.shieldWallTimer>0){S().prevented=(S().prevented||0)+c.prevented;S().vowUntil=C.clock+5;}else if(hit(c,"Radiant Smite")&&S().vowUntil>C.clock){if(C.once(c.cast,"vow")){c.cast.vowDamage=Math.min(A(),(S().prevented||0)*.5);S().prevented=0;}c.amount+=c.cast.vowDamage||0;}});
  R("paladin_guard_anchor","dash",c=>{if(c.type==="aegis"&&livingBosses().some(t=>distance(c.destination,t)<140+t.radius))C.shield(.1);});
  R("paladin_guard_shared","guard",c=>{if(c.type==="bulwark"){C.shield(isPartySyncActive()?.1:.15);C.support?.("shield",.1,180,3,c.cast.id);}});
  R("paladin_guard_martyr","shieldBreak",()=>{if(C.ready("martyr",2))C.pulse(player.x,player.y,100,A()*.8,"Martyr Spark");});
  R("paladin_guard_cap","lethal guard",c=>{if(c.event==="lethal")shieldSave("Unfallen",.25,3,1.5,c);else if(c.type==="bulwark"){C.shield(.05);C.support?.("shield",.05,180,3,c.cast.id);}});
  R("paladin_judgment_damage","cast",c=>{if(c.type==="smite")c.factor*=1.25;});
  R("paladin_judgment_radius","cast hit",c=>{if(c.event==="cast"&&c.type==="smite")c.radiusMultiplier=1.25;if(c.event==="hit"&&hit(c,"Radiant Smite")){const p=pointFromAngle(c.cast.origin.x,c.cast.origin.y,c.cast.angle,98);if(distance(p,c.target)<20)c.amount+=A()*.25;}});
  R("paladin_judgment_mark","afterHit",c=>{if(hit(c,"Radiant Smite")){c.target.judgmentTimer=5;c.target.rogueJudgmentOwner=multiplayer.id;syncTargetStatus(c.target,"judgment");}});
  R("paladin_judgment_chain","afterHit",c=>{if(hit(c,"Radiant Smite")&&C.once(c.cast,"chainVerdict")){const near=targetsNear(c.target,160)[0];if(near)damageBossTarget(near,c.dealt*.6,"Chain Verdict",{proc:true});else C.pulse(c.target.x,c.target.y,12,c.dealt*.25,"Chain Verdict");}});
  R("paladin_judgment_trial","afterHit",c=>{if(!hit(c,"Radiant Smite"))return;const t=c.target;if(t.holyBurnTimer>0){const time=Math.min(2,t.holyBurnTimer);t.holyBurnTimer-=time;C.pulse(t.x,t.y,12,time*t.holyBurnDamage*4,"Trial By Fire");}else{t.holyBurnTimer=2;t.holyBurnTick=.5;t.holyBurnDamage=A()*.05;}});
  R("paladin_judgment_day","smiteEnd",c=>{if(C.count("judgmentDay")%3===0)C.effect({type:"judgmentZone",...c.cast.center,r:c.cast.r,ttl:3,pulseTimer:0});});
  R("paladin_judgment_appeal","afterHit",c=>{if(hit(c,"Radiant Smite")&&c.judgedBefore&&C.once(c.cast,"appeal")){C.heal(.05);C.support?.("lowestHeal",.03,180,0,c.cast.id);}});
  R("paladin_judgment_cap","hit afterHit",c=>{if(!hit(c,"Radiant Smite"))return;if(c.event==="hit"&&c.target.judgmentTimer>0){c.amount*=1.6;c.cast.finalJudged=true;}else if(c.event==="afterHit"){if(c.cast.finalJudged){c.target.judgmentTimer=0;if(C.once(c.cast,"finalRefund"))C.refund(0,currentAbilities()[0].cooldown*.2);}else{c.target.judgmentTimer=5;c.target.rogueJudgmentOwner=multiplayer.id;}}});

  R("bard_chord_damage","cast",c=>{if(c.type==="chord")c.factor*=1.25;});
  R("bard_chord_harmonic","cast",c=>{if(c.type==="chord")c.factor*=1+.1*activeLocalBardSongTypes().size/(1.3+.2*activeLocalBardSongTypes().size);});
  R("bard_chord_extend","chordEnd",c=>{if(c.hits.length)for(const e of ownBardSongEffects()){const extra=Math.min(.75,2.25-(e.extension||0));e.extension=(e.extension||0)+extra;e.ttl+=extra;}});
  R("bard_chord_bass_cleave","cast",c=>{if(c.type==="chord"){c.halfAngle=Math.PI/3;c.rangeMultiplier=1.2;}});
  R("bard_chord_dissonance","afterHit",c=>{if(hit(c,"Power Chord")){c.target.dissonanceUntil=C.clock+3;}});
  R("bard_chord_echo","chordEnd",c=>{if(C.count("echoNote")%2===0)repeat(c.cast,.4,.3);});
  R("bard_chord_shatter","hit",c=>{if(hit(c,"Power Chord")){const n=[c.target.markedShots,c.target.poisonStacks,c.target.burnTimer,c.target.bleedTimer,c.target.judgmentTimer].filter(v=>v>0).length;c.amount*=1+Math.min(.45,n*.15);}});
  R("bard_chord_cap","cast chordEnd",c=>{if(c.event==="cast"&&c.type==="chord"&&activeLocalBardSongTypes().size>=3)c.factor*=1.6;else if(c.event==="chordEnd"&&c.songs>=3&&c.hits.length)C.pulse(c.cast.origin.x,c.cast.origin.y,180,A()*.5,"Grand Finale");});
  R("bard_chord_encore_blast","death chordEnd",c=>{if(c.event==="death"&&hit(c,"Power Chord")&&C.once(c.cast,"encore")){const near=targetsNear(c.target,240)[0];if(near)C.pulse(near.x,near.y,12,c.dealt*.5,"Encore Blast");}else if(c.event==="chordEnd"&&c.hits.some(t=>!t.mazeEnemy)&&C.count("encoreBoss")%3===0&&C.once(c.cast,"encore"))repeat(c.cast,.5,.15);});
  R("bard_hymn_damage","song",c=>{if(c.type==="battle")c.field.damageBuff+=.1;});
  R("bard_hymn_speed","song",c=>{if(c.type==="battle")c.field.attackSpeedBuff+=.15;});
  R("bard_hymn_radius","song",c=>{if(["battle","quickstep"].includes(c.type)){c.field.r*=1.3;c.field.grace=1;}});
  R("bard_hymn_marching","song",c=>{if(c.type==="battle")c.field.speedBuff=.12;});
  R("bard_hymn_war","cast",c=>{if(c.type==="chord"&&C.inside("bardBattleHymn"))c.factor*=1.25;});
  R("bard_hymn_haste","song",c=>{if(c.type==="battle")c.field.cooldownRecovery=.15;});
  R("bard_hymn_rally","cast",c=>{if(["chord","bash","quake","whirlwind","mark","storm","trap","blast","meteor","backstab","cloud","smite","consecration"].includes(c.type)&&C.inside("bardBattleHymn")&&C.ready("rally",.75))C.pulse(player.x,player.y,132,A()*.2,"Rallying Echo");});
  R("bard_hymn_cap","song afterHit",c=>{if(c.event==="song"&&c.type==="battle"){c.field.ttl+=2;c.field.maxTtl+=2;}else if(basic(c)&&strongestBardSongValue("battle","damageBuff")>0&&C.count("anthem")%3===0)C.pulse(c.target.x,c.target.y,70,A()*.5,"Anthem Pulse");});
  R("bard_heal_power","song healPulse",c=>{if(c.event==="song"&&c.type==="healing"){c.field.healAmount*=1.25;c.field.overhealShield=true;}else if(c.event==="healPulse"&&c.field.overhealShield&&c.overheal>0)C.shield(Math.min(.05,c.overheal/player.maxHp),2);});
  R("bard_heal_duration","song",c=>{if(c.type==="healing"){c.field.ttl+=1.5;c.field.maxTtl+=1.5;}});
  R("bard_heal_armor","song defense",c=>{if(c.event==="song"&&c.type==="healing"){c.field.reduction=.12;c.field.grace=.5;}else if(c.event==="defense"&&strongestBardSongValue("healing","reduction")>0)c.multiplier*=.88;});
  R("bard_heal_cleanse","song",c=>{if(c.type==="healing"){if(player.pickleSlowTimer>0)player.pickleSlowTimer=0;else if(player.chillStacks>0)player.chillStacks=0;else if(player.tacoGreaseTimer>0)player.tacoGreaseTimer=0;c.field.cleanse=true;}});
  R("bard_heal_reprise","healingTick",()=>{const e=C.inside("bardHealingBallad");if(e){S().lastBallad=e;S().wasInBallad=true;}else if(S().wasInBallad){S().wasInBallad=false;const id=S().lastBallad.id;if(!S()["reprise-"+id]){S()["reprise-"+id]=true;C.later(1,()=>C.heal(.04));}}});
  R("bard_heal_rescue","healPulse",c=>{if(c.before<player.maxHp*.35&&!c.field.rescueUsed){c.field.rescueUsed=true;C.heal(.08);}});
  R("bard_heal_sanctuary","song",c=>{if(c.type==="healing")c.field.slowFactor=.7;});
  R("bard_heal_cap","healingTick song",c=>{if(c.event==="healingTick"&&player.hp>0&&player.hp<player.maxHp*.25&&!S().saves.encore){S().saves.encore=true;startBardSong("healing",{encore:true});C.shield(.1);const e=C.field("bardHealingBallad");if(e)e.ttl=3;}else if(c.event==="song"&&c.type==="healing")C.shield(.03,2);});

  for(const [id] of Arcade.rogueData.nodes)if(!C.rules.has(id))throw new Error("Missing talent implementation: "+id);
})();
