/* Extend the existing host protocol without moving gameplay authority to peers. */
const RogueNetwork = { pending:new Map(),seen:new Map(),songGrace:new Map(),supportSeen:new Set(),visualSeen:new Set(),endSeq:0,
  accept(peer,kind,seq){if(!Number.isInteger(seq)||seq<1)return false;const key=multiplayer.phaseSeq+":"+peer+":"+kind;if(seq<=(this.seen.get(key)||0))return false;this.seen.set(key,seq);return true;},
  phase(event){return event.bossKind===boss.kind&&event.phaseSeq===multiplayer.phaseSeq;},
  support(event){if(this.supportSeen.has(event.id))return;this.supportSeen.add(event.id);if(player.dead||player.room!==event.room||distance(player,event)>event.r)return;if(event.action==="shield")RogueCombat.shield(event.percent,event.duration);else RogueCombat.heal(event.percent);},
  resolveSupport(peerId,e){const actor=peerId===multiplayer.id?player:multiplayer.peers.get(peerId);if(!actor||actor.dead||!this.phase(e)||!Number.isFinite(e.percent)||e.percent<=0||e.percent>.1||e.r>200||e.duration>3)return;
    const near=[...(multiplayer.room?.players||[])].filter(m=>m.id!==peerId).filter(m=>{const p=m.id===multiplayer.id?player:multiplayer.peers.get(m.id);return p&&!p.dead&&p.room===player.room&&distance(p,actor)<=e.r;});
    if(e.action==="lowestHeal")near.sort((a,b)=>{const x=a.id===multiplayer.id?player:multiplayer.peers.get(a.id),y=b.id===multiplayer.id?player:multiplayer.peers.get(b.id);return x.hp/x.maxHp-y.hp/y.maxHp;}).splice(1);
    const packet={...e,kind:"support-result",recipients:near.map(m=>m.id),x:actor.x,y:actor.y,room:actor.room};sendMultiplayerEvent(packet);if(packet.recipients.includes(multiplayer.id))this.support(packet);
  }
};

function installRogueNetwork(){
  targetStatusGroups.judgment.push("rogueJudgmentOwner");
  const oldStatus=mergeRemoteTargetStatus;mergeRemoteTargetStatus=function(t,g,s,a){const result=oldStatus(t,g,s,a);if(g==="judgment"&&typeof s.rogueJudgmentOwner==="string")t.rogueJudgmentOwner=s.rogueJudgmentOwner;return result;};
  const oldDamage=damageBossTarget,oldEvent=handleMultiplayerEvent,oldIntent=applyRemoteHitIntent,oldSnapshot=multiplayerSnapshot,oldSend=sendMultiplayerEvent,oldAttack=spawnRemoteAttackVisual,oldSongs=bardSongsAffectingPlayer,oldBardSnapshot=bardSongSnapshot,oldSync=sendGauntletSync,oldApply=applyRemoteGauntletSync,oldPhase=applyPartyPhase;
  damageBossTarget=function(t,amount,source,options={}){
    if(!t||t.hp<=0)return false;if(!shouldSendHostHitIntent(t,source,options))return oldDamage(t,amount,source,options);
    const c=RogueCombat.hitContext(t,amount,source,options);if(!c.proc)RogueCombat.emit("hit",c);
    const descriptor=targetSyncDescriptor(t),seq=++multiplayer.intentSeq;
    RogueNetwork.pending.set(seq,{c,before:t.hp,phase:multiplayer.phaseSeq,at:RogueCombat.clock});
    sendMultiplayerEvent({kind:"hit-intent",seq,phaseSeq:multiplayer.phaseSeq,bossKind:boss.kind,...descriptor,source,baseAmount:Math.round(c.amount),options:{proc:c.proc,dot:Boolean(options.dot),rangedBasic:Boolean(options.rangedBasic),markedBonus:Boolean(options.markedBonus),markedMultiplier:c.options.markedMultiplier||1.45,tacoBypassGuard:Boolean(options.tacoBypassGuard),rogue:true,sushiSegment:Number.isInteger(options.sushiSegment)?options.sushiSegment:null}});return true;
  };
  applyRemoteHitIntent=function(peerId,e){if(!isMultiplayerHost()||!RogueNetwork.phase(e))return;const target=resolveRemoteSyncedTarget(e),peer=validPeerIntent(peerId,e.encounter==="gauntlet"?"maze":"arena");if(!target||!peer||!validPeerTargetIntent(peer,e,target,Number(e.baseAmount)))return;if(!RogueNetwork.accept(peerId,"hit",e.seq))return;
    const before=target.hp,mark=target.markedShots||0,judged=target.judgmentTimer>0;e.options={...e.options,attackerId:peerId};oldIntent(peerId,e);
    sendMultiplayerEvent({kind:"rogue-hit-result",recipient:peerId,seq:e.seq,bossKind:e.bossKind,phaseSeq:e.phaseSeq,encounter:e.encounter,targetId:e.targetId,targetKind:e.targetKind,dealt:before-target.hp,before,hp:target.hp,lastMark:mark>0&&target.markedShots===0,markedShots:target.markedShots||0,markedTimer:target.markedTimer||0,judgedBefore:judged});
  };
  handleMultiplayerEvent=function(peerId,e){if(!e)return;if((e.kind==="attack"||e.kind==="ability")&&e.seq!==undefined){const key=peerId+":"+multiplayer.phaseSeq+":"+e.kind+":"+e.seq;if(RogueNetwork.visualSeen.has(key))return;RogueNetwork.visualSeen.add(key);if(RogueNetwork.visualSeen.size>512)RogueNetwork.visualSeen.delete(RogueNetwork.visualSeen.values().next().value);}
    if(e.kind==="run-end"){if(!isHostPeer(peerId)||!RogueNetwork.phase(e)||!RogueNetwork.accept(peerId,"end",e.seq))return;for(const id of e.bosses||[])Arcade.progress.record("bosses",id);for(const id of e.contracts||[])Arcade.progress.record("contracts",id);RogueGame.end(e.reason,e.final,false);return;}
    if(e.kind==="route-choice"){if(isHostPeer(peerId)&&RogueNetwork.phase(e)&&["boss","contract"].includes(e.route))RogueGame.route=e.route;return;}
    if(e.kind==="contract-state"){if(!isHostPeer(peerId)||isMultiplayerHost()||!RogueNetwork.phase(e)||!mazeState?.contract||!RogueNetwork.accept(peerId,"contract-state",e.seq))return;mazeState.contract=cloneSyncObject(e.contract);mazeState.exitOpen=Boolean(e.exitOpen);mazeState.rewardPending=Boolean(e.rewardPending)&&!mazeState.rewardChosen;for(const enemy of mazeState.enemies){const remote=e.enemies?.find(x=>x.id===enemy.id);if(remote)Object.assign(enemy,remote);}if(e.contract.finished&&!e.contract.failed)Arcade.progress.record("contracts",boss.kind);return;}
    if(e.kind==="contract-action"){if(!isMultiplayerHost()||!RogueNetwork.phase(e)||!RogueNetwork.accept(peerId,"contract-action",e.seq))return;const actor=validPeerIntent(peerId,"maze");if(actor)RogueContracts.interact(actor,Boolean(e.pressed),Boolean(e.held),.1);return;}
    if(e.kind==="rogue-dot-result"){if(!isHostPeer(peerId)||e.recipient!==multiplayer.id||!RogueNetwork.phase(e)||!RogueNetwork.accept(peerId,"dot",e.seq))return;const target=activeBosses().find(t=>e.targetId?t.id===e.targetId:t.kind===e.targetKind);if(!target)return;target.hp=e.hp;const c=RogueCombat.hitContext(target,e.dealt,e.source,{proc:true,dot:true});c.before=e.before;c.dealt=e.dealt;RogueCombat.emit("afterDamage",c);if(e.hp<=0)RogueCombat.emit("death",c);return;}
    if(e.kind==="rogue-hit-result"){if(!isHostPeer(peerId)||e.recipient!==multiplayer.id)return;const pending=RogueNetwork.pending.get(e.seq);RogueNetwork.pending.delete(e.seq);if(!pending||pending.phase!==multiplayer.phaseSeq||!RogueNetwork.phase(e)||!(e.dealt>0))return;const c=pending.c;c.before=e.before;c.dealt=e.dealt;c.lastMark=e.lastMark;c.judgedBefore=e.judgedBefore;c.target.hp=Math.max(0,e.hp);c.target.markedShots=e.markedShots;c.target.markedTimer=e.markedTimer;RogueCombat.emit("afterDamage",c);if(!c.proc)RogueCombat.emit("afterHit",c);if(e.hp<=0&&(!c.proc||c.options.dot))RogueCombat.emit("death",c);return;}
    if(e.kind==="support-pulse"){if(isMultiplayerHost()&&RogueNetwork.accept(peerId,"support",e.seq))RogueNetwork.resolveSupport(peerId,e);return;}
    if(e.kind==="support-result"){if(isHostPeer(peerId)&&RogueNetwork.phase(e)&&e.recipients?.includes(multiplayer.id))RogueNetwork.support(e);return;}
    if(e.kind==="relic-ready"){if(isMultiplayerHost()&&RogueNetwork.phase(e)&&intermission){intermission.ready ||= new Set();intermission.ready.add(peerId);RogueRelics.updateReady();}return;}
    if(e.kind==="ability"&&RogueCombat.has("bard_hymn_rally")){const actor=multiplayer.peers.get(peerId),damaging={melee:[0,1,2],ranger:[0,1,3],mage:[0,1],rogue:[0,1],paladin:[0,1],bard:[0]};if(actor&&damaging[e.classKey]?.includes(e.abilityIndex)&&RogueNetwork.phase(e)&&RogueCombat.inside("bardBattleHymn",actor)&&RogueCombat.ready("rally",.75))RogueCombat.pulse(actor.x,actor.y,132,RogueCombat.A()*.2,"Rallying Echo");}
    if(e.kind==="party-retry"&&!RogueGame.practice())return;
    return oldEvent(peerId,e);
  };
  sendMultiplayerEvent=function(e){if(e.kind==="attack"||e.kind==="ability"){const aimed=RogueTraining.aim(),origin=aimed.origin;e={...e,origin,phaseSeq:multiplayer.phaseSeq,angle:aimed.angle,seq:e.kind==="ability"?multiplayer.id+":"+(RogueCombat.current?.id||++RogueCombat.sequence):e.seq};}if(e.kind==="gauntlet-sync"&&mazeState?.contract)e={...e,contract:cloneSyncObject(mazeState.contract)};return oldSend(e);};
  spawnRemoteAttackVisual=function(peer,e){if(e.origin){e={...e,x:e.origin.x-Math.cos(e.angle)*24,y:e.origin.y-Math.sin(e.angle)*24};}oldAttack(peer,e);};
  const oldRemoteAbility=spawnRemoteAbilityVisual;spawnRemoteAbilityVisual=function(peer,e){const n=remoteAbilityEffects.length;oldRemoteAbility(peer,e);for(const fx of remoteAbilityEffects.slice(n))fx.origin=e.origin;};
  multiplayerSnapshot=function(){const s=oldSnapshot();s.activeTalents=Array.from(runState.learnedTalents);s.runMode=RogueGame.practice()?"practice":runState.mode;s.runEnded=RogueGame.finished;s.supportZones=abilityEffects.filter(e=>e.type==="holyStrip"&&e.ttl>0).map(e=>({type:e.type,x:e.x,y:e.y,x2:e.x2,y2:e.y2,r:e.r,ttl:e.ttl}));return s;};
  bardSongSnapshot=function(){return ownBardSongEffects().map(e=>{const s=oldBardSnapshot().find(s=>s.songType===bardSongType(e))||{};return {...s,id:e.id,cooldownRecovery:e.cooldownRecovery||0,reduction:e.reduction||0,grace:e.grace||0,overhealShield:Boolean(e.overhealShield),rescue:Boolean(RogueCombat.has("bard_heal_rescue")),cleanse:Boolean(e.cleanse),reprise:Boolean(RogueCombat.has("bard_heal_reprise")),slowFactor:e.slowFactor||0};});};
  bardSongsAffectingPlayer=function(){const active=oldSongs(),now=RogueCombat.clock;for(const s of active){const key=s.id||s.songType+":"+s.x+":"+s.y;RogueNetwork.songGrace.set(key,{song:s,until:now+(s.grace||0)});}for(const [key,g] of RogueNetwork.songGrace){if(g.until<now)RogueNetwork.songGrace.delete(key);else if(!active.some(s=>s.id===g.song.id)&&g.song.ttl>0)active.push(g.song);}return active;};
  RogueCombat.support=function(action,percent,r,duration,id){if(!isPartySyncActive())return;const e={kind:"support-pulse",seq:++multiplayer.intentSeq,phaseSeq:multiplayer.phaseSeq,bossKind:boss.kind,action,percent,r,duration,id:multiplayer.id+":"+id+":"+action,x:player.x,y:player.y,room:player.room};if(isMultiplayerHost())RogueNetwork.resolveSupport(multiplayer.id,e);else sendMultiplayerEvent(e);};
  // Contract properties travel with the same gauntlet snapshot used for recovery.
  applyRemoteGauntletSync=function(peer,e){oldApply(peer,e);if(isHostPeer(peer)&&e.contract&&mazeState){mazeState.contract=cloneSyncObject(e.contract);if(e.contract.finished&&!e.contract.failed)Arcade.progress.record("contracts",boss.kind);}};
  applyPartyPhase=function(e,...args){const contract=e.phase==="reward"&&mazeState?.contract;oldPhase(e,...args);if(contract)Arcade.progress.record("contracts",boss.kind);};
  const oldStatusApply=applyRemoteTargetStatus;applyRemoteTargetStatus=function(peer,e){const t=resolveRemoteSyncedTarget(e);if(t&&["poison","bleed","burn"].includes(e.statusGroup))t[e.statusGroup+"Owner"]=peer;oldStatusApply(peer,e);};
  const oldUpdate=updateAbilities;updateAbilities=function(dt){oldUpdate(dt);for(const [seq,p] of RogueNetwork.pending)if(RogueCombat.clock-p.at>8)RogueNetwork.pending.delete(seq);
    const best=bardSongsAffectingPlayer().find(s=>(s.songType||bardSongType(s))==="healing");
    if(!best&&RogueNetwork.lastBallad?.reprise&&!RogueCombat.has("bard_heal_reprise")){const id="reprise-"+RogueNetwork.lastBallad.id;if(!RogueNetwork.supportSeen.has(id)){RogueNetwork.supportSeen.add(id);RogueCombat.later(1,()=>RogueCombat.heal(.04));}}RogueNetwork.lastBallad=best;
    if(best?.cleanse&&!RogueCombat.has("bard_heal_cleanse")&&!RogueNetwork.supportSeen.has("cleanse-"+best.id)){RogueNetwork.supportSeen.add("cleanse-"+best.id);if(player.pickleSlowTimer>0)player.pickleSlowTimer=0;else if(player.chillStacks>0)player.chillStacks=0;else player.tacoGreaseTimer=0;}
  };
}
