/* Short, readable commitment/recovery cycles built on the food bosses' controllers. */
const RogueBosses={
  tips:{cola:"Straw aim locks before firing · burst a bubble to vent pressure",burger:"Bait the charge into a grill · strike during the stagger",fries:"Read the alternating firing lane · close in during the heat vent",trio:"Choose a bottle · breaking one interrupts the other two",sauce:"Hit the mixer during its windup to open a dry island",shake:"One health bar · bait the scoop slam, then punish the flavor break",nacho:"Choose a quadrant before it locks · strike behind the guard",pizza:"Break a topping station to silence its pattern for nine seconds",donut:"Three stages · follow the ring gap, then use the recovery",taco:"Bait the wall ram · crack the shell and attack its exposed filling",sushi:"Leave the curved lane · strike the glowing roll to stagger the serpent"},
  recover(t= boss,duration=1.3){t.rogueRecovery=Math.max(t.rogueRecovery||0,duration);t.rogueExposed=duration;t.attackTimer=Math.max(t.attackTimer||0,duration+.5);t.swingTimer=Math.max(t.swingTimer||0,duration+.5);t.destination=null;if(["ketchup","mustard","mayo"].includes(t.kind)){t.state="recovering";t.stateTimer=duration;}RogueCombat.effect({type:"rogueImpact",x:t.x,y:t.y,r:t.radius+14,ttl:.3});},
  grills(){return [{x:world.arena.x+95,y:world.arena.y+120,r:50},{x:world.arena.x+world.arena.w-95,y:world.arena.y+world.arena.h-120,r:50}];},
  parts(){return boss.kind==="pizza"?(boss.toppingParts||[]):[];},
  bite(dt){if(!["burger","fries"].includes(boss.kind))return;if(boss.rogueRecovery>0)return;boss.biteCooldown=(boss.biteCooldown??2)-dt;
    if(boss.biteWarn>0){boss.biteWarn-=dt;if(boss.biteWarn<=0){const p=pointFromAngle(boss.x,boss.y,boss.biteAngle,60);if(distance(p,player)<56+player.radius)damagePlayer(14,"Committed bite");this.recover(boss,.9);boss.biteCooldown=2;}return;}
    if(boss.biteCooldown<=0&&distance(boss,player)<130){boss.biteAngle=Math.atan2(player.y-boss.y,player.x-boss.x);boss.biteWarn=.7;const p=pointFromAngle(boss.x,boss.y,boss.biteAngle,60);RogueCombat.effect({type:"bossBiteWarning",...p,r:56,ttl:.7});}
  }
};
function installRogueBosses(){
  const oldCreate=createBoss;createBoss=function(kind){const b=oldCreate(kind);if(kind==="cola"){b.maxHp=Math.round(b.maxHp*.62);b.hp=b.maxHp;}if(kind==="shake"){b.maxHp=scaledBossHp("shake",1450);b.hp=b.maxHp;}if(kind==="donut")b.totalPhases=3;return b;};
  // Initial boss already exists when adapters install.
  if(boss.kind==="cola"){boss.maxHp=Math.round(boss.maxHp*.62);boss.hp=boss.maxHp;}
  const oldLoad=loadBoss;loadBoss=function(kind){oldLoad(kind);if(kind==="pizza")boss.toppingParts=["pepperoni","oven","crust"].map((name,i)=>({kind:"topping-"+name,name:name+" station",x:world.arena.x+180+i*230,y:world.arena.y+150+(i%2)*350,radius:24,hp:scaledCombatHealth(120),maxHp:scaledCombatHealth(120),shieldTimer:0,disabledUntil:0}));};
  const oldActive=activeBosses,oldDefeat=handleBossDefeated,oldHealth=bossHealthSummary;
  activeBosses=function(){const base=oldActive();return player.room==="arena"&&boss.kind==="pizza"?base.concat(RogueBosses.parts()):base;};
  bossHealthSummary=function(){if(player.room==="maze"&&mazeState?.contract)return {hp:mazeState.contract.completed,maxHp:mazeState.contract.goal};if(player.room==="arena"&&boss.kind==="pizza")return {hp:boss.hp,maxHp:boss.maxHp};return oldHealth();};
  handleBossDefeated=function(t){if(t.kind.startsWith("topping-")){t.disabledUntil=RogueCombat.clock+9;RogueBosses.recover(boss,.8);showFloat(t.name+" disabled · 9s");return;}if(t===boss&&boss.kind==="pizza")RogueBosses.parts().forEach(p=>p.hp=0);if(boss.kind==="trio"&&t.kind!=="trainingDummy"){hazards=[];for(const other of condimentBosses)if(other!==t&&other.hp>0)RogueBosses.recover(other,1.4);}return oldDefeat(t);};
  const oldUpdate=updateBossCombatLocal;updateBossCombatLocal=function(dt){if(boss.rogueRecovery>0){boss.rogueRecovery=Math.max(0,boss.rogueRecovery-dt);boss.rogueExposed= Math.max(0,boss.rogueExposed-dt);player.attackCooldown-=dt;boss.animationTime+=dt;return;}if(["burger","fries"].includes(boss.kind))boss.swingTimer=99;oldUpdate(dt);RogueBosses.bite(dt);if(boss.kind==="pizza")for(const part of RogueBosses.parts())if(part.hp<=0&&RogueCombat.clock>=part.disabledUntil)part.hp=part.maxHp;};
  const oldHit=applyDamageBossTargetLocal;applyDamageBossTargetLocal=function(t,amount,source,options={}){if(t.rogueExposed>0)amount*=1.2;if(t.kind==="nacho"&&t.invulnerableTimer<=0&&RogueCombat.rear(t,multiplayer.peers.get(options.attackerId)||player))amount*=1.15;let segment;if(t===boss&&boss.kind==="sushi"&&Number.isInteger(options.sushiSegment)){segment=sushiSegments().find(s=>s.index===options.sushiSegment);if(segment)amount*=segment.weak?2.05:.82;}const result=oldHit(t,amount,source,options);if(result&&segment?.weak&&!options.proc&&(!isPartySyncActive()||isMultiplayerHost())&&RogueCombat.ready("sushiBreak",3)){rotateSushiWeakSegment(segment.index+2,1.5);boss.sushiWeakFlashTimer=.72;boss.sushiPunishTimer=1.3;RogueBosses.recover(boss,1.3);}if(result&&t===boss&&boss.kind==="sauce"&&boss.state==="winding"&&!options.proc){boss.mixerDamage=(boss.mixerDamage||0)+amount;if(boss.mixerDamage>=RogueCombat.A()*1.5){boss.mixerDamage=0;boss.state="recovering";boss.stateTimer=1.6;hazards=hazards.filter(h=>distance(h,boss)>180);RogueBosses.recover(boss,1.6);showFloat("Mixer interrupted · dry island");}}return result;};
  const oldControl=applyRemoteHazardControl;applyRemoteHazardControl=function(peer,e){const bubble=e.action==="destroy"&&hazards.some(h=>h.type==="colaBubble"&&e.hazardIds?.includes(h.syncId));oldControl(peer,e);if(bubble&&isMultiplayerHost()&&hazards.some(h=>h.type==="colaBubble"&&h.ttl<=0)){hazards=hazards.filter(h=>h.type!=="fizzBurst");boss.pressureTimer=Math.max(boss.pressureTimer,4);RogueBosses.recover(boss,1.3);}};
  const oldRadius=damageTargetsInRadius;damageTargetsInRadius=function(x,y,r,amount,source,hitTargets=[],options={}){let hit=false;if(player.room==="arena"&&boss.kind==="sushi"&&boss.hp>0&&!hitTargets.includes(boss)){const s=sushiSegments().filter(s=>Math.hypot(s.x-x,s.y-y)<=r+s.r).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(s){hit=damageBossTarget(boss,amount,source,{...options,sushiSegment:s.index});if(hit)hitTargets.push(boss);}}const hits=oldRadius(x,y,r,amount,source,hitTargets,options);return hit?[boss,...hits]:hits;};
  const oldCone=RogueCombat.cone;RogueCombat.cone=function(c,range,half,damage,source=c.name){if(player.room!=="arena"||boss.kind!=="sushi")return oldCone.call(this,c,range,half,damage,source);const s=sushiSegments().find(s=>Math.hypot(s.x-c.origin.x,s.y-c.origin.y)<=range+s.r&&Math.abs(angleDifference(Math.atan2(s.y-c.origin.y,s.x-c.origin.x),c.angle))<=half);return s&&damageBossTarget(boss,playerDamage(damage),source,{cast:c,sushiSegment:s.index})?[boss]:[];};
  const oldValidate=validPeerTargetIntent;validPeerTargetIntent=function(peer,e,target,amount){if(target===boss&&boss.kind==="sushi"&&Number.isInteger(e.options?.sushiSegment)){const s=sushiSegments().find(s=>s.index===e.options.sushiSegment);if(s)return oldValidate(peer,e,{...target,x:s.x,y:s.y,radius:s.r},amount);}return oldValidate(peer,e,target,amount);};
  const oldCanDestroy=canRemoteDestroyHazard;canRemoteDestroyHazard=h=>h.type==="colaBubble"||oldCanDestroy(h);
  const oldCola=spawnBigColaPattern;spawnBigColaPattern=function(){const turn=boss.roguePattern=(boss.roguePattern||0)+1;if(turn%3===1)spawnStrawSnipe();else if(turn%3===2)spawnColaBubbles(boss.phase===1?3:4);else spawnSodaSpill();};
  const oldStraw=spawnStrawSnipe;spawnStrawSnipe=function(){oldStraw();boss.ventAt=RogueCombat.clock+1.2;boss.attackTimer=Math.max(boss.attackTimer,2.8);};
  const oldProjectile=updatePlayerProjectiles;
  // Training's swept updater calls this before ordinary target collision.
  RogueBosses.hitBubble=function(p,x,y){if(player.room!=="arena"||boss.kind!=="cola")return false;const h=hazards.find(h=>h.type==="colaBubble"&&h.ttl>0&&rogueSegmentHits(x,y,p.x,p.y,{...h,radius:h.r},p.r));if(!h)return false;if(isPartySyncActive()&&!isMultiplayerHost()){sendHazardControlIntent("destroy",[h.syncId],{x:h.x,y:h.y,radius:h.r+10});}h.ttl=0;hazards=hazards.filter(x=>x!==h&&x.type!=="fizzBurst");if(!isPartySyncActive()||isMultiplayerHost()){boss.pressureTimer=Math.max(boss.pressureTimer,4);RogueBosses.recover(boss,1.3);}return true;};
  const oldBurger=updateBigBurgerCharge;updateBigBurgerCharge=function(dt){const charging=boss.state==="burgerCharging";oldBurger(dt);if(charging&&boss.state==="moving"&&RogueBosses.grills().some(g=>distance(g,boss)<g.r+boss.radius)){RogueBosses.recover(boss,2);showFloat("Grill stagger · exposed layer");}};
  spawnFryMachineGun=function(){boss.frySide=(boss.frySide||0)+1;const angle=(boss.frySide%2?-1:1)*.75+Math.atan2(player.y-boss.y,player.x-boss.x);hazards.push({type:"machineGun",x:boss.x,y:boss.y,angle,sweepSpeed:boss.frySide%2?.18:-.18,warn:.85,ttl:1.65,fireTimer:0,damageTimer:0,damage:11});boss.ventAt=RogueCombat.clock+1.8;setBossAnimation("machineGun");};
  spawnCurlyFriesPattern=function(){if((boss.fryPattern=(boss.fryPattern||0)+1)%3===0){spawnGreasePuddles(1);boss.ventAt=RogueCombat.clock+2;}else spawnFryMachineGun();};
  const oldShake=updatePeanutBusterShake;updatePeanutBusterShake=function(dt){const next=boss.hp/boss.maxHp<=.33?3:boss.hp/boss.maxHp<=.66?2:1;if(next!==boss.phase){boss.phase=next;hazards=[];RogueBosses.recover(boss,1.8);showFloat(next===2?"Brain Freeze · flavor break":"Buster Cup · flavor break");}oldShake(dt);};
  const oldWin=winFight;winFight=function(){if(boss.kind==="shake"){const phases=boss.totalPhases;boss.totalPhases=boss.phase;oldWin();boss.totalPhases=phases;return;}oldWin();};
  updateDonutPhase=function(){const next=boss.hp/boss.maxHp<=.33?3:boss.hp/boss.maxHp<=.66?2:1;if(next!==boss.phase){boss.phase=next;boss.enraged=next===3;boss.donutHoles=createDonutHoles(next===3?2:1);hazards=[];RogueBosses.recover(boss,1.6);}boss.donutGauntletActive=false;};
  isDonutHolePhase=()=>boss.phase>=2;isDonutFinalPhase=()=>boss.phase===3;
  const oldRing=spawnGlazeRing;spawnGlazeRing=function(count){oldRing(Math.min(2,count));boss.ventAt=RogueCombat.clock+3.6;};
  const oldNacho=updateNachoLibre;updateNachoLibre=function(dt){const mode=boss.quadrantMode;oldNacho(dt);boss.invulnerableTimer=Math.min(boss.invulnerableTimer,1.2);if(mode!=="idle"&&boss.quadrantMode==="idle")RogueBosses.recover(boss,1.4);};
  const oldPizza=spawnPizzaPattern;spawnPizzaPattern=function(){const off=RogueBosses.parts().filter(p=>p.hp<=0).map(p=>p.kind);if(off.includes("topping-pepperoni")){if(off.includes("topping-oven"))spawnPizzaDash();else spawnOvenZones(2);}else if(off.includes("topping-crust"))spawnPepperoniVolley(5,.5);else oldPizza();};
  const oldOven=spawnOvenZones;spawnOvenZones=function(...args){if(boss.kind==="pizza"&&RogueBosses.parts().some(p=>p.kind==="topping-oven"&&p.hp<=0))return;oldOven(...args);};
  const oldCrust=spawnPizzaCrustWalls;spawnPizzaCrustWalls=function(...args){if(RogueBosses.parts().some(p=>p.kind==="topping-crust"&&p.hp<=0))return;oldCrust(...args);};
  hitSushiSegment=function(p,x=p.x,y=p.y){if(p.hitSushiBody)return false;const segment=sushiSegments().find(s=>rogueSegmentHits(x,y,p.x,p.y,{...s,radius:s.r},p.r));if(!segment)return false;p.hitSushiBody=true;p.hitTargets ||= [];p.hitTargets.push(boss);if(p.fireBlast){p.x=segment.x;p.y=segment.y;explodeFireBlast(p,boss,{sushiSegment:segment.index});return true;}if(p.markedShot)markBossTarget(boss);const hit=damageBossTarget(boss,p.damage,p.markedShot?"Marked Shot":p.ability?p.source||"Ability":"Shot",{projectile:p,sushiSegment:segment.index,rangedBasic:p.tag==="Ranged"&&!p.ability,markedBonus:p.tag==="Ranged"&&!p.ability,proc:Boolean(p.proc)});if(hit&&p.tag==="Rogue"&&!p.ability){applyPoisonStack(boss);applyExposedStack(boss,p);}return hit;};
  const oldDraw=drawBoss;drawBoss=function(){oldDraw();if(boss.kind==="burger")for(const g of RogueBosses.grills()){ctx.fillStyle="#25344b";ctx.fillRect(g.x-35,g.y-25,70,50);ctx.fillStyle="#efbe55";for(let y=-16;y<=16;y+=8)ctx.fillRect(g.x-27,g.y+y,54,4);}if(boss.kind==="pizza")for(const part of RogueBosses.parts()){ctx.fillStyle=part.hp>0?"#efbe55":"#69dec3";ctx.fillRect(part.x-24,part.y-24,48,48);ctx.fillStyle="#101522";ctx.font="14px Consolas";ctx.textAlign="center";ctx.fillText(part.name.split(" ")[0].slice(0,3).toUpperCase(),part.x,part.y+5);ctx.fillStyle="#fff1cd";ctx.fillRect(part.x-24,part.y-32,48*part.hp/part.maxHp,4);}};
  const oldAbilities=updateAbilities;updateAbilities=function(dt){oldAbilities(dt);if(player.room==="arena"&&boss.ventAt&&RogueCombat.clock>=boss.ventAt&&(!isPartySyncActive()||isMultiplayerHost())){boss.ventAt=0;RogueBosses.recover(boss,1.3);}};
}
